#!/usr/bin/env bash
set -euo pipefail

# Auto-generated by robotwin2_evidence_window_plan.py.
# Commands are dry-run unless this plan was generated with --execute.
# Run root: /home/yihao_hyh/efv_runs/robotwin2_evidence_window_20260613_k4

echo '=== handover_block seeds 0-3 ==='
EXECUTE=0 GPU_ID=auto TASK_CONFIG=demo_clean_k5 CANDIDATE_PRESET=targeted_energy_matched TASKS=handover_block SEEDS=0-3 RUN_ANALYSIS_AFTER=0 RESUME_PARTIAL=0 REQUIRE_CANDIDATES_PER_CASE=24 NUM_SWEEP_SEEDS=10 scripts/robotwin2_bounded_window_launcher.sh /home/yihao_hyh/efv_runs/robotwin2_evidence_window_20260613_k4

echo '=== place_object_basket seeds 0-3 ==='
EXECUTE=0 GPU_ID=auto TASK_CONFIG=demo_clean_k5 CANDIDATE_PRESET=targeted_energy_matched TASKS=place_object_basket SEEDS=0-3 RUN_ANALYSIS_AFTER=0 RESUME_PARTIAL=0 REQUIRE_CANDIDATES_PER_CASE=24 NUM_SWEEP_SEEDS=10 scripts/robotwin2_bounded_window_launcher.sh /home/yihao_hyh/efv_runs/robotwin2_evidence_window_20260613_k4

echo '=== stack_bowls_two seeds 0-3 ==='
EXECUTE=0 GPU_ID=auto TASK_CONFIG=demo_clean_k5 CANDIDATE_PRESET=targeted_energy_matched TASKS=stack_bowls_two SEEDS=0-3 RUN_ANALYSIS_AFTER=0 RESUME_PARTIAL=0 REQUIRE_CANDIDATES_PER_CASE=24 NUM_SWEEP_SEEDS=10 scripts/robotwin2_bounded_window_launcher.sh /home/yihao_hyh/efv_runs/robotwin2_evidence_window_20260613_k4

echo '=== stack_blocks_two seeds 0-3 ==='
EXECUTE=0 GPU_ID=auto TASK_CONFIG=demo_clean_k5 CANDIDATE_PRESET=targeted_energy_matched TASKS=stack_blocks_two SEEDS=0-3 RUN_ANALYSIS_AFTER=0 RESUME_PARTIAL=0 REQUIRE_CANDIDATES_PER_CASE=24 NUM_SWEEP_SEEDS=10 scripts/robotwin2_bounded_window_launcher.sh /home/yihao_hyh/efv_runs/robotwin2_evidence_window_20260613_k4

echo '=== press_stapler seeds 0-2 ==='
EXECUTE=0 GPU_ID=auto TASK_CONFIG=demo_clean_k5 CANDIDATE_PRESET=targeted_energy_matched TASKS=press_stapler SEEDS=0-2 RUN_ANALYSIS_AFTER=0 RESUME_PARTIAL=0 REQUIRE_CANDIDATES_PER_CASE=24 NUM_SWEEP_SEEDS=10 scripts/robotwin2_bounded_window_launcher.sh /home/yihao_hyh/efv_runs/robotwin2_evidence_window_20260613_k4

echo '=== dry-run finalize command ==='
printf '%s\n' 'PYTHONPATH=src PYTHON_BIN=python3 REQUIRE_CANDIDATES_PER_CASE=24 NUM_SWEEP_SEEDS=10 scripts/robotwin2_finalize_run.sh /home/yihao_hyh/efv_runs/robotwin2_evidence_window_20260613_k4 handover_block place_object_basket stack_bowls_two stack_blocks_two press_stapler'
